"""Added RUN faction

Revision ID: c5c40d77d162
Revises: e06ce34cdcbc
Create Date: 2021-01-24 19:20:23.223415

"""
from alembic import op
import sqlalchemy as sa

from libs.models.Guild import Guild


# revision identifiers, used by Alembic.
revision = 'c5c40d77d162'
down_revision = 'e06ce34cdcbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(Guild.__table__, [
        {
            "name": "RUN", "chat_id": -1001234212002
        }
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
